services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./volumes/pb_data:/pb_data
      - ./volumes/pb_public:/pb_public
      - ./volumes/pb_migrations:/pb_migrations
    environment:
      PB_DEBUG: "true"
