name: pb_cli
description: The pocketbase CLI.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  cli_async_redux:
    path: packages/cli_async_redux
  cli_utils:
    path: packages/cli_utils
  collection: ^1.19.1
  dotenv: ^4.2.0
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  io: ^1.0.5
  json_annotation: ^4.9.0
  mason_logger: ^0.3.3

  pocketbase: ^0.23.0
  stack_trace: ^1.12.1

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  pro_lints: ^5.0.0

executables: 
  pb_cli: bin/pb_cli.dart
