name: pb_cli
description: The pocketbase CLI.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dotenv: ^4.2.0
  http: ^1.5.0
  io: ^1.0.5
  mason_logger: ^0.3.3
  meta: ^1.17.0
  path: ^1.9.1
  pocketbase: ^0.23.0

dev_dependencies:
  pro_lints: ^5.0.0

executables: 
  pb_cli: bin/pb_cli.dart
